[project]
name = "reffer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.15.1",
    "polars>=1.25.2",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.39",
    "streamlit>=1.43.2",
]
