from enum import Enum


class EntryType(str, Enum):
    ARTICLE = "article"
    BOOK = "book"
    BOOKLET = "booklet"
    CONFERENCE = "conference"
    INBOOK = "inbook"
    INCOLLECTION = "incollection"
    INPROCEEDINGS = "inproceedings"
    MANUAL = "manual"
    MASTERTHESIS = "masterthesis"
    MISC = "misc"
    PHDTHESIS = "phdthesis"
    PROCEEDINGS = "proceedings"
    TECHREPORT = "techreport"
    UNPUBLISHED = "unpublished"


class BibField(str, Enum):
    ADDRESS = "address"
    ANNOTE = "annote"
    AUTHOR = "author"
    BOOKTITLE = "booktitle"
    CHAPTER = "chapter"
    CITEKEY = "citekey"
    DATE = "date"
    DOI = "doi"
    EDITION = "edition"
    EDITOR = "editor"
    ENTRY_TYPE = "entry_type"
    HOWPUBLISHED = "howpublished"
    INSTITUTION = "institution"
    ISBN = "isbn"
    ISSN = "issn"
    JOURNAL = "journal"
    MONTH = "month"
    MRCLASS = "mrclass"
    MRNUMBER = "mrnumber"
    MRREVIEWER = "mrreviewer"
    MRREVIEWNUMBER = "mrreviewnumber"
    NOTE = "note"
    NUMBER = "number"
    ORGANIZATION = "organization"
    PAGES = "pages"
    PUBLISHER = "publisher"
    SCHOOL = "school"
    SERIES = "series"
    TITLE = "title"
    TYPE = "type"
    URL = "url"
    VOLUME = "volume"
    YEAR = "year"
